---
title: "R package"
author: "Harivansh Luchmun"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction


# First function
```{r first}

Math4753Hari::myci(x=c(9,9,1,9,9,9))

```


# Second function
```{r second}
Math4753Hari::myncurve(2, 4, 3)
```


# Third function
```{r third}
Math4753Hari::ntickets(100, 0.3, 0.9)

```


# Fourth function
```{r fourth}
Math4753Hari::boot2pval(x1=c(9,9,1,9,9,9), x2=c(23,5,4, 5,9, 2))

```
#Fifth function
```{r fifth}
Math4753Hari::mycltp(20, 10000, 4)

```

#Sixth function
```{r sixth}
Math4753Hari::square(2)

```

#Seventh function
```{r seventh}
Math4753Hari::myboot(x=c(10,20,40,50,60,1,20,40,20))

```


#Eight Function
```{r eighth}
Math4753Hari::mymaxlik(lfun=logbin, x=c(9,9,1,9,9,9),param=seq(0,1,length=1000))
```

#Ninth Function
```{r}
Math4753Hari::check_p_binom(8, 15, 0.4)
```
# The github repository



This is the address of my GITHUB repository:
<https://github.com/HarivanshL/Math4753Hari>
